[package]
name = "muscle_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
frankenstein = "0.23"
thiserror = "1.0.38"
